name: Ruby Gem

on:
  push:
  pull_request:
  schedule:
    # * is a special character in YAML so you have to quote this string, runs on each day of the week at 00:00 UTC
    - cron: '0 0 * * *'


jobs:
  test:
    name: Test
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        # Due to https://github.com/actions/runner/issues/849, we have to use quotes for '3.0'
        ruby: ['2.6', '2.7', '3.0', '3.1', head, jruby, jruby-head, truffleruby, truffleruby-head]
        exclude:
          # Exclude combinations of os and version
          - os: windows-latest
            ruby: truffleruby
          - os: windows-latest
            ruby: truffleruby-head
    runs-on: ${{ matrix.os }}
    permissions:
      contents: read
      packages: write

    steps:
    - uses: actions/checkout@v3
    - uses: ruby/setup-ruby@v1
      with:
        ruby-version: ${{ matrix.ruby }}
        bundler-cache: false # runs 'bundle install' and caches installed gems automatically
    - name: Run tests
      env:
        DEBUG: true
      run: |
        gem install bundler
        bundle --version
        which bundler
        gem update bundler
        bundle --version
        which bundler
        bundle install
        bundle exec rake test

  build:
    name: Build + Publish
    runs-on: ubuntu-latest
    needs: test
    if: github.ref == 'refs/heads/main'
    permissions:
      contents: write
      packages: write

    steps:
    - uses: actions/checkout@v3
    - uses: ruby/setup-ruby@v1
      with:
        ruby-version: '3.1'

    - name: Build
      run: |
        mkdir -p $HOME/.gem
        touch $HOME/.gem/credentials
        chmod 0600 $HOME/.gem/credentials
        printf -- "---\n:rubygems_api_key: ${GEM_HOST_API_KEY}\n" > $HOME/.gem/credentials
        gem build jarbler.gemspec
        JARBLER_RELEASE=`ls jarbler-*.gem | sed 's/jarbler-//' | sed 's/\.gem//'`
        echo "JARBLER_RELEASE=$JARBLER_RELEASE" >> $GITHUB_ENV
        # Ensure that exit code != 0 does not stop the build
        set +e
        echo "Check for existing release tag"
        gh release view $JARBLER_RELEASE -R ${{ github.repository }}
        if [[ $? -eq 0 ]]; then
          echo "Github release tag $JARBLER_RELEASE already exists"
        else
          echo "Github release tag $JARBLER_RELEASE does not exist yet"
          gh release create $JARBLER_RELEASE "./jarbler-${JARBLER_RELEASE}.gem#jarbler-${JARBLER_RELEASE}.gem: use also 'gem install jarbler'" --notes "Continuous development" --title "Jarbler $JARBLER_RELEASE"
          if [ $? -eq 0 ]; then
            echo "Release created"
          else
            echo "gh release create failed"
            exit 1
          fi
        fi
        echo "Checking rubygems.org for RELEASE=$JARBLER_RELEASE"
        gem search jarbler | grep jarbler | grep $JARBLER_RELEASE
        if [[ $? -eq 0 ]]; then
          echo "RELEASE=$JARBLER_RELEASE already exists on rubygems.org, no push executed"
        else
          echo "RELEASE=$JARBLER_RELEASE does not exist on rubygems.org yet"
          echo "Manual execution of 'gem push jarbler-${JARBLER_RELEASE}.gem' required! This will fix the CI at next run"
          exit 1
          # rdoc --all --ri --op doc
          # gem push *.gem
        fi
      env:
        GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        # GH_TOKEN: ${{ github.token }}
        # GEM_HOST_API_KEY: "${{secrets.RUBYGEMS_AUTH_TOKEN}}"

    - name: Put gem file into artifact
      if: always()
      uses: actions/upload-artifact@v1
      with:
        name: jarbler-${{ env.JARBLER_RELEASE }}.gem
        path: jarbler-${{ env.JARBLER_RELEASE }}.gem
