name: Ruby Gem

on:
  push:
  pull_request:
  schedule:
    # * is a special character in YAML so you have to quote this string, runs on each day of the week at 00:00 UTC
    - cron: '0 0 * * *'


jobs:
  test:
    name: Test
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest]
        # os: [ubuntu-latest, macos-latest, windows-latest]
        # Due to https://github.com/actions/runner/issues/849, we have to use quotes for '3.0'
        ruby: ['3.1']
        # ruby: ['2.6', '2.7', '3.0', '3.1', head, jruby, jruby-head, truffleruby, truffleruby-head]
        exclude:
          # Exclude combinations of os and version
          - os: windows-latest
            ruby: truffleruby
          - os: windows-latest
            ruby: truffleruby-head
    runs-on: ${{ matrix.os }}
    permissions:
      contents: read
      packages: write

    steps:
    - uses: actions/checkout@v3
    - uses: ruby/setup-ruby@v1
      with:
        ruby-version: ${{ matrix.ruby }}
        bundler-cache: true # runs 'bundle install' and caches installed gems automatically
    - name: Run tests
      env:
        DEBUG: true
      run: |
        gem install bundler
        bundle install
        bundle exec rake test

  build:
    name: Build + Publish
    runs-on: ubuntu-latest
    needs: test
    #if: github.ref == 'refs/heads/main'
    permissions:
      contents: write
      packages: write

    steps:
    - uses: actions/checkout@v3
    - uses: ruby/setup-ruby@v1
      with:
        ruby-version: '3.1'

    - name: Build
      run: |
        mkdir -p $HOME/.gem
        touch $HOME/.gem/credentials
        chmod 0600 $HOME/.gem/credentials
        printf -- "---\n:rubygems_api_key: ${GEM_HOST_API_KEY}\n" > $HOME/.gem/credentials
        gem build jarbler.gemspec
        JARBLER_RELEASE=`ls jarbler-*.gem | sed 's/jarbler-//' | sed 's/\.gem//'`
        echo "JARBLER_RELEASE=$JARBLER_RELEASE" >> $GITHUB_ENV
        echo "Checking rubygems.org for RELEASE=$JARBLER_RELEASE"
        set +e
        gem search jarbler | grep jarbler | grep $JARBLER_RELEASE
        if [[ $? -eq 0 ]]; then
          echo "RELEASE=$JARBLER_RELEASE already exists on rubygems.org, no push executed"
        else
          echo "RELEASE=$JARBLER_RELEASE does not exist on rubygems.org yet"
          echo "Manual execution of 'gem push *.gem' required"
          # rdoc --all --ri --op doc
          # gem push *.gem
        fi
        ls -l
      # env:
        # GEM_HOST_API_KEY: "${{secrets.RUBYGEMS_AUTH_TOKEN}}"

    - name: Create Release
      id: create_release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # This token is provided by Actions, you do not need to create your own token
      with:
        tag_name: ${{ env.JARBLER_RELEASE }}
        release_name: Jarbler ${{ env.JARBLER_RELEASE }}
        draft: false
        prerelease: false

    - name: Put gem file into artifact
      if: always()
      uses: actions/upload-artifact@v1
      with:
        name: jarbler-${{ env.JARBLER_RELEASE }}.gem
        path: jarbler-*.gem
